---

- name: Ensure APT HTTPS Transport is installed.
  apt:
    name: apt-transport-https
    state: present

- name: Set the packagecloud repository name based on the version.
  set_fact:
    varnish_packagecloud_repo: "varnish{{ varnish_version|replace('.', '') }}"

- name: Add packagecloud.io Varnish apt key.
  apt_key:
    url: https://packagecloud.io/varnishcache/{{ varnish_packagecloud_repo }}/gpgkey
    state: present

- name: Add packagecloud.io Varnish apt repository.
  apt_repository:
    repo: "{{ varnish_apt_repo }}"
    state: present

- name: Ensure Varnish is installed.
  apt:
    name: varnish
    state: present

- name: Copy Varnish default VCL.
  template:
    src: "{{ varnish_default_vcl_source_name }}"
    dest: "/etc/varnish/default.vcl"
    owner: root
    group: root
    mode: 0644
  notify: restart varnish

- name: Override varnishncsa systemd service for log format
  template:
    src: systemd/varnishncsa-override.conf.j2
    dest: /etc/systemd/system/varnishncsa.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify: restart varnishncsa
  when: varnishncsa_x_forwarded_for_enabled

- name: Enable and start varnishncsa service
  service:
    name: varnishncsa
    state: started
    enabled: true
